app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bang/', include('bang.urls'))
]

app/bang/urls.py
from django.urls import path
from .views import training_view
from . import views


app_name = 'bang'
urlpatterns = [
#TRAINING PATHS by Sean
    path('training/', training_view.TrainingListView.as_view(), name='training'),
    path('training_detail/<int:pk>/', training_view.TrainingDetailView.as_view(), name='training_detail'),
    path('training_detail/<int:pk>/training_delete/', training_view.DeleteEnabledDetailView.as_view(), name='training_delete'),
    path('training_detail/<int:pk>/edit', training_view.TrainingUpdate.as_view(), name='training_edit'),
    path('training/add/', training_view.TrainingFormView.as_view(), name='training_form'),
    path('', views.IndexView.as_view(), name = 'index'),
########## 
# COMPUTER PATHS by Erin
    path('computers/', views.ComputerListView.as_view(), name='computer_list'),
    path('computers/<int:pk>/', views.ComputerDetailView.as_view(), name='computer_detail'),
    path('computers/add/', views.ComputerFormView.as_view(), name='computer_form'),
    path('computers/<int:pk>/computer_delete/', views.ComputerDeleteView.as_view(), name='computer_delete'),
##########
# DEPARTMENT PATHS by Raf
    path('departments/', views.DepartmentListView.as_view(), name='departments'),
    path('departments/<int:pk>/', views.DepartmentDetailView.as_view(), name='department_detail'),
    path('departments/add/', views.DepartmentFormView.as_view(), name='departments_form'),
##########
# EMPLOYEES PATHS by Hayley
    path('employees/', views.EmployeesListView.as_view(), name='employees'),
    path('employees/<int:pk>/', views.EmployeesDetailView.as_view(), name='employees_detail'),
    path('employees/<int:pk>/edit', views.EmployeesEditView.as_view(), name='employees_edit'),
    path('employees/add/', views.EmployeesFormView.as_view(), name='employees_form')
]

app/bang/models/computer.py
#Author: Erin Agobert
from django.db import models
from django.urls import reverse


class Computer(models.Model):
    """ Model represents employee computers"""
    make = models.CharField(max_length=30)
    model = models.CharField(max_length=30)
    purchase_date = models.DateField()

    class Meta:
        db_table = "computer"

    # def get_absolute_url(self):
    #     return reverse('computer_list', kwargs={'pk': self.pk})

    def __str__(self):
        return self.make

app/bang/models/department.py
# Author: Raf
from django.db import models


'''
Department Model

Model for Departments include the following:
    dept_name is a string defaulted to ""
'''


class Department(models.Model):
    dept_name = models.CharField(default="", max_length=30)

    class Meta:
        db_table = "department"

    def __str__(self):
        return self.dept_name

app/bang/models/employees.py
from django.db import models
from django.urls import reverse
from .department import Department
from .computer import Computer
from .training import Training

class Employees(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    start_date = models.DateField()
    supervisor = models.BooleanField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE,)
    computer = models.ForeignKey(Computer, on_delete=models.CASCADE, blank=True, null=True,)
    training = models.ManyToManyField(Training)


    class Meta:
        db_table = 'employees'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

# Author: Raf
    def get_absolute_url(self):
        return reverse("bang:employees_detail", kwargs={"pk": self.pk})

app/bang/models/training.py
#Sean Irwin
from django.db import models
from django.urls import reverse



#lays out basics of all training events and links it to employees with a many to many table with employees
class Training(models.Model):
    name = models.CharField(default="", max_length=30)
    description = models.CharField(default="", max_length=100)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    max_attendees = models.IntegerField(default=1)


    class Meta:
        db_table = "training"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("bang:training_detail", kwargs={"pk": self.pk})

app/bang/forms/computer_form.py
from django import forms
from bang.models import Computer


class ComputerForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = ['make', 'model', 'purchase_date']

app/bang/forms/department_form.py
from django import forms
from bang.models import Department


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['dept_name']

app/bang/forms/employees_form.py
from django import forms
from bang.models import Employees


class EmployeesForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = ['first_name', 'last_name', 'start_date', 'department', 'supervisor', 'computer', 'training']

#########
# Author: Raf
class EmployeesEditForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = ['last_name', 'department', 'computer', 'training'] # Still need to add training

app/bang/forms/training_form.py
from django import forms
from bang.models import Training


class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = ['name', 'description', 'start_date', 'end_date', 'max_attendees']

app/bang/views/computer_view.py
#Author: Erin Agobert
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import DeleteView
from bang.models import Computer
from bang.forms import ComputerForm


class ComputerListView(ListView):
    """ View represents a list of employee computers"""
    model = Computer
    context_object_name = 'computer_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "computers"
        return context

class ComputerDetailView(DetailView):
    """View represents a detail view of an assigned computer"""
    model = Computer

class ComputerFormView(FormView):
    """
    API endpoint that allows a COMPUTER FORM to be viewed and edited.
    """
    template_name = 'bang/computer_form.html'
    form_class = ComputerForm
    success_url = '/bang/computers/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'computer_form'
        return context

    def form_valid(self, form):
        form.save()
        return super(ComputerFormView, self).form_valid(form)

class ComputerDeleteView(DeleteView):
    """ View represents deleting an employee """
    model = Computer
    template_name = 'bang/computer_confirm_delete.html'
    success_url = '/bang/computers'

    def delete(self, request, *args, **kwargs):
        """ Calls the delete method """
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

app/bang/views/department_view.py
#Author: Raf
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, FormView, DetailView
from bang.models import Department
from bang.forms import DepartmentForm


"""
These are all the views for DEPARTMENT
    -List View
    -Form View
    -Detail View
"""

class DepartmentListView(ListView):
    """
    API endpoint that allows all DEPARTMENTS to be viewed.
    """
    model = Department
    context_object_name = 'department_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'departments'
        return context

class DepartmentFormView(FormView):
    """
    API endpoint that allows a DEPARTMENT FORM to be viewed.
    """
    template_name = 'bang/department_form.html'
    form_class = DepartmentForm
    success_url = '/bang/departments/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'departments_form'
        return context

    def form_valid(self, form):
        form.save()
        return super(DepartmentFormView, self).form_valid(form)

class DepartmentDetailView(DetailView):
    """
    API endpoint that allows a single DEPARTMENT to be viewed as well as the EMPLOYEES assigned to that particular DEPARTMENT.
    """
    model = Department

app/bang/views/employees_view.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, FormView, DetailView, UpdateView
from bang.models import Employees

from bang.forms import EmployeesForm, EmployeesEditForm

class EmployeesListView(ListView):
    model = Employees
    context_object_name = 'employees_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'employees'
        return context

class EmployeesFormView(FormView):
    """
    API endpoint that allows an employee form to be viewed and edited.
    """
    template_name = 'bang/employees_form.html'
    form_class = EmployeesForm
    success_url = '/bang/employees/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'employees_form'
        return context

    def form_valid(self, form):
        form.save()
        return super(EmployeesFormView, self).form_valid(form)

########
# Author: Raf - Edit view
class EmployeesEditView(UpdateView):
    '''
    API endpoint that allows an employee to be edited
    '''
    model = Employees
    form_class = EmployeesEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'employees_edit'
        context['title_action'] = 'Edit an employee'
        return context

class EmployeesDetailView(DetailView):
    model = Employees

app/bang/views/index_view.py
# Author: Raf
from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'bang/index.html'

    def location(self):
        return 'home'

app/bang/views/training_view.py
#Sean Irwin
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, FormView, DetailView, CreateView, DeleteView, UpdateView
from bang.models import Training
from bang.forms import TrainingForm
import datetime
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.exceptions import ImproperlyConfigured
from django.forms import models as model_forms
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View
from django.views.generic.detail import (
    BaseDetailView, SingleObjectMixin, SingleObjectTemplateResponseMixin,
)
# from .forms import -- Forms will be imported here

#creates an instance of current date to compare event date with and restrict deletion
now = datetime.date.today()



#creates a reference to link template of html and model to the database and actual object information
class TrainingListView(ListView):
    """
    API endpoint that allows TRAINING to be viewed.
    """
    model = Training
    context_object_name = 'training_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'training'
        return context


class TrainingDetailView(DetailView):
    model = Training
    
    

class DeletionMixin:
    """Provide the ability to delete objects."""
    success_url = None

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        if (self.object.end_date > now):
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            return HttpResponseRedirect(success_url)

    # Add support for browsers which only accept GET and POST for now.
    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        if self.success_url:
            return self.success_url.format(**self.object.__dict__)
        else:
            raise ImproperlyConfigured(
                "No URL to redirect to. Provide a success_url.")

class DeleteEnabledDetailView(DeletionMixin, TrainingDetailView):
    success_url = "/bang/training"
    context_object_name = 'training_delete'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

# class TrainingDeleteView(DeleteView):
#     model = Training
#     success_url = "/bang/training"
#     context_object_name = ''

    #changes default behavior of delete to disqualify past events from deletion

    # def delete(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     if (self.object.end_date > now):
    #         return super(TrainingDeleteView, self).delete(
    #             request, *args, **kwargs)
    #     else:
    #         raise Http404("Object you are looking for doesn't exist")

class TrainingFormView(FormView):
    """
    API endpoint that allows an employee form to be viewed and edited.
    """

    template_name = 'bang/training_form.html'
    form_class = TrainingForm
    success_url = '/bang/training/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location'] = 'training_form'
        return context

    def form_valid(self, form):
        form.save()
        return super(TrainingFormView, self).form_valid(form)

class TrainingUpdate(UpdateView):
    model = Training
    fields = ['name', 'description', 'start_date', 'end_date', 'max_attendees']
    
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if (self.object.end_date > now):
            return super().post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        if (self.object.end_date > now):
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            return HttpResponseRedirect(success_url)


    

app/bang/templates/bang/computer_confirm_delete.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/computer.css' %}">

<div class='computer_delete'>
<h1>Computer Deletion</h1>
{% for employee in computer.employees_set.all %}


<p>You cannot delete this computer.  Please return to :  <a href="{% url 'bang:computer_list' %}">Computer List </a> and choose an unassigned computer</p>

{% empty %}

    <form method="post">
    
    {% csrf_token %}

    <p>Are you sure you want to delete "{{ computer.make }} {{ computer.model}}"?</p>
    <input type="submit" value="Confirm">
    </form>
    
    <a href="{% url 'bang:computer_detail' computer.id %}">Return to Computer {{computer.id}}</a>

{% endfor %}
</div>

app/bang/templates/bang/computer_detail.html
<!-- Author: Erin -->
{% extends "bang/index.html" %}

{% block main_stuff %}
{% include "bang/navbar.html" with nav_location=location %}


{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/computer.css' %}">

<div class='computer_detail'>
    <h1>Computer {{computer.id}}</h1>

    <h2>Make: {{computer.make}}</h2>
    <h2>Model: {{computer.model}}</h2>
    <h2>Purchase Date: {{computer.purchase_date}}</h2>

    {% for employee in computer.employees_set.all %}
    <h2>Assigned Employee:  {{employee.first_name}} {{employee.last_name}}</h2>
    {% endfor %}
    <div class='delete_div'>
    <a href="{% url 'bang:computer_delete' computer.id %}">
        <div class='delete'>
            <p>Delete</p>
        </div>
    </a>
    </div>
</div>
{% endblock main_stuff %}

app/bang/templates/bang/computer_list.html
{% extends 'bang/index.html' %}

{% block main_stuff %}
{% include 'bang/navbar.html' with nav_location=location %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/computer.css' %}">


<h1>Computer List</h1>

{% if computer_list %}
<div class='container'>
    <ul class='computer_ul'>
    {% for computer in computer_list %}
        <li>
            <a href="{% url 'bang:computer_detail' computer.id %}">
                <div class='computer_card'>
                    <p>{{computer.make}} {{computer.model}}</p>
                    <p>{{computer.purchase_date}}</p>
                </div>
            </a>
        </li>
    {% endfor %}
    </ul>
    <div class='float_clear'></div>
</div>
{% else %}
    <p>No computers are saved.</p>
{% endif %}
{% endblock main_stuff %}

app/bang/templates/bang/employees_detail.html
<!-- Author: Hayley / Levi -->
{% extends "bang/index.html" %}

{% block main_stuff %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/employee.css' %}"> 

{% include "bang/navbar.html" with nav_location=location %}

<div class='employee_detail'>
<h1>Employee Profile</h1>

<h2>Name: {{employees.first_name}} {{employees.last_name}}</h2>
<h3>Department: {{employees.department}}</h3>
<h3>Start Date: {{employees.start_date}}</h3>
<h3>Computer: {{employees.computer}} </h3>
<h3>Training Programs:</h3>
<ul>
{% for training in employees.training.all %}
    <li>
        <p>{{training.name}}</p>
    </li>
{% endfor %}
</ul>
<div class='edit_div'>
    <a href="{% url 'bang:employees_edit' employees.id %}">
        <div class='edit'>
            <p>Edit</p>
        </div>
    </a>
</div>
</div>
{% endblock main_stuff %}

<!-- Maybe we'll want to show all the employees in each department? -->

app/bang/templates/bang/employees_form.html
<!-- Author: Hayley-->
{% extends "bang/index.html" %}

{% block main_stuff %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/employee.css' %}"> 

<div class='employee_form'>
<h3>Add/Edit an Employee</h3>

<form method='post'>
    {% csrf_token %}
    {{ form }}
    <br>
    <input type="submit" value="Save Employee">
  </form>
</div>
{% endblock main_stuff %}

app/bang/templates/bang/employees_list.html
<!-- Author: Hayley / Levi -->
{% extends 'bang/index.html' %} 
{% block main_stuff %} 

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/employee.css' %}"> 

{% include "bang/navbar.html" with nav_location=location %}

<div class='employee_list'>
<h1>Bangazon LLC Employees </h1>

<ul>
    {% for employees in employees_list %}
    <li>
        <a href="{% url 'bang:employees_detail' employees.id %}">
            <div class='employee_card'>
                <p>{{employees.first_name}} {{employees.last_name}}</p>
            </div>
        </a>
        <!-- placehold text would go here -->
    </li>
    {% endfor %}
</ul>
<div class='float_clear'></div>
</div>
{% endblock main_stuff %}

app/bang/templates/bang/index.html
<!-- Author: Raf -->

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bang/style.css' %}">

<div class='header'>
    <h1>Welcome to BANGAZON!</h1>
</div>

{% block main_stuff %}
    {% include "bang/navbar.html" with nav_location=view.location %}
    {% comment %} Including nav_bar in each template so we can pass the location to it each time {% endcomment %}
    <div class='app_description'>
        <p>This application is intended to manage the internal structure of the fictional Bangazon LLC. It is used for handling the database the stores details of the departments, employees, computers, and training programs available to the organization. It is built using Python, Django, and SQLite3.</p>
    </div>
{% endblock main_stuff %}

app/bang/templates/bang/nav_computer.html
<h3>Computer Sub Navigation</h3>
<nav>
    <ul class='sub_nav'>
    {% if nav_location != 'computers' %}
        <li>
        <form action='/bang/computers' method='GET'>
            <input type='submit' value='Home'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'computers_form' %}
        <li>
        <form action='/bang/computers/add' method='GET'>
            <input type='submit' value='Add New'>
        </form>
        </li>
    {% endif %}
    </ul>
</nav>

app/bang/templates/bang/nav_department.html
<h3>Department Sub Navigation</h3>
<nav>
    <ul class='sub_nav'>
    {% if nav_location != 'departments' %}
        <li>
        <form action='/bang/departments' method='GET'>
            <input type='submit' value='Home'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'departments_form' %}
        <li>
        <form action='/bang/departments/add' method='GET'>
            <input type='submit' value='Add New'>
        </form>
        </li>
    {% endif %}
    </ul>
</nav>

app/bang/templates/bang/nav_employee.html
<h3>Employee Sub Navigation</h3>
<nav>
    <ul class='sub_nav'>
    {% if nav_location != 'employees' %}
        <li>
        <form action='/bang/employees' method='GET'>
            <input type='submit' value='Home'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'employees_form' %}
        <li>
        <form action='/bang/employees/add' method='GET'>
            <input type='submit' value='Add New'>
        </form>
        </li>
    {% endif %}
    </ul>
</nav>

app/bang/templates/bang/navbar.html
<nav>
    <ul class='main_nav'>
    {% if nav_location != 'home' %}
        <li>
        <form action='/bang/' method='GET'>
            <input type='submit' value='Home'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'computers' %}
        <li>
        <form action='/bang/computers' method='get'>
            <input type='submit' value='Computers'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'departments' %}
        <li>    
        <form action='/bang/departments' method='get'>
            <input type='submit' value='Departments'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'employees' %}
        <li>
        <form action='/bang/employees' method='get'>
            <input type='submit' value='Employees'>
        </form>
        </li>
    {% endif %}
    {% if nav_location != 'training' %}
        <li>
        <form action='/bang/training' method='get'>
            <input type='submit' value='Training'>
        </form>
        </li>
    {% endif %}
    </ul>
</nav>
<div class='sub'>
    {% if nav_location == 'computers' %}
        {% include "bang/nav_computer.html" with nav_location=location %}
    {% endif %}
    {% if nav_location == 'departments' %}
        {% include "bang/nav_department.html" with nav_location=location %}
    {% endif %}
    {% if nav_location == 'employees' %}
        {% include "bang/nav_employee.html" with nav_location=location %}
    {% endif %}
    {% if nav_location == 'training' %}
        {% include "bang/nav_training.html" with nav_location=location %}
    {% endif %}
</div>

app/bang/templates/bang/training_detail.html
<!-- Sean Irwin -->
{% extends "bang/index.html" %}

{% block main_stuff %}
{% include "bang/navbar.html" with nav_location=location %}

<h1>Training Details</h1>

<h2>{{training.name}}</h2>

<p>Start Date: {{training.start_date}}</p>
<p>End Date: {{training.end_date}}</p>
<p>Description: {{training.description}}</p>
<p>Max Attendees: {{training.max_attendees}}</p>

{% if training.end_date > now %}
<p><a href="{% url 'bang:training_edit' training.id %}">edit</a></p>

<form action="{% url 'bang:training_delete' pk=training.id %}" method='post'>
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
{% endif %}
<h2>Employee - Training</h2>
{% for training_relationship in training.employees_set.all %}
    <li>{{training_relationship}}</li>
{% endfor %}



{% endblock main_stuff %}

app/bang/templates/bang/training_form.html
<!-- Sean Irwin -->
{% extends "bang/index.html" %}

{% block main_stuff %}

<h3>Add a new Training</h3>

<form method='post'>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save Training">
  </form>

{% endblock main_stuff %}

app/bang/templates/bang/training_list.html
{% extends "bang/index.html" %}

{% block main_stuff %}
{% include "bang/navbar.html" with nav_location=location %}
<h1>These Are Made Up Programs from TrainingListTemplateView </h1>

<ul>
  {% for training in training_list %}
    <li>
      <a href="{% url 'bang:training_detail' training.id %}">{{training.name}}</a>
    </li>
  {% endfor %}
</ul>
{% endblock main_stuff %}